### ISSUE TITLE
Timestamp verification error msg

### ISSUE THREAD

**Issue by iamvkv** [BlockchainCommons/rsign-did#10]
From http://3xcaaswwserqnox56z7d7wifwyxm2jsdv4fniffym5jwncqx3qr7uzid.onion/

text.txt.minisig and text.txt.minisig.ots files uploaded to verify a timestamp. 

The result is:

"Assuming target hash is '936ba496231e0e3c99aea7c6253552f190525ba11e8ced4f0f22b6b170f67bb6' Got 1 attestation(s) from https://alice.btc.calendar.opentimestamps.org Got 1 attestation(s) from https://bob.btc.calendar.opentimestamps.org Calendar https://finney.calendar.eternitywall.com: Error: certificate has expired Got 1 attestation(s) from https://btc.calendar.catallaxy.com Lite-client verification, assuming block 00000000000000000004320fbeb24def54f1ef93555249790cb3fb92e54fbabe is valid Lite-client verification, assuming block 00000000000000000009367eea9fc1266cc67091ef5c35bd80bf583da145c05b is valid Lite-client verification, assuming block 000000000000000000050cd52d41014c6a2d3b6a4fb605de6b82886ae97de006 is valid Success! Bitcoin block 661927 attests existence as of 2020-12-18 GMT"

The verification is successful but there is one error message regarding "https://finney.calendar.eternitywall.com: Error: certificate has expired"

Is this something we need to resolve?

**Comment by gorazdko** [comment]
Tnx for reporting.

At the moment it works:

`Assuming target hash is '936ba496231e0e3c99aea7c6253552f190525ba11e8ced4f0f22b6b170f67bb6' Got 1 attestation(s) from https://bob.btc.calendar.opentimestamps.org Got 1 attestation(s) from https://btc.calendar.catallaxy.com Got 1 attestation(s) from https://alice.btc.calendar.opentimestamps.org Got 1 attestation(s) from https://finney.calendar.eternitywall.com Lite-client verification, assuming block 00000000000000000004320fbeb24def54f1ef93555249790cb3fb92e54fbabe is valid Lite-client verification, assuming block 00000000000000000004320fbeb24def54f1ef93555249790cb3fb92e54fbabe is valid Lite-client verification, assuming block 000000000000000000050cd52d41014c6a2d3b6a4fb605de6b82886ae97de006 is valid Lite-client verification, assuming block 00000000000000000009367eea9fc1266cc67091ef5c35bd80bf583da145c05b is valid Success! Bitcoin block 661927 attests existence as of 2020-12-18 GMT`

Of course these are public calendars not run by us. If the issue reoccurs and persist we'll ask for support there https://finney.calendar.eternitywall.com/

Closing for now.
