### ISSUE TITLE
Overwriting the signature and signing the files by successive commands

### ISSUE THREAD

**Issue by henkvancann** [BlockchainCommons/rsign-did#3]
In the following test, I was able to wreck earlier result without warning. 

$ cargo run sign testfile.txt -t "Just something to add to it"
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/rsign sign testfile.txt -t 'Just something to add to it'`
Password: 
Deriving a key from the password and decrypting the secret key... done
~/app-container/torgap-sig-cli-rust (master)
$ cargo run verfiy testfile.txt -p rsign.pub
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/rsign verfiy testfile.txt -p rsign.pub`
error: The subcommand 'verfiy' wasn't recognized
	Did you mean 'verify'?

If you believe you received this message in error, try re-running with 'rsign -- verfiy'

USAGE:
    rsign [SUBCOMMAND]

For more information try --help
~/app-container/torgap-sig-cli-rust (master)
$ cargo run verify testfile.txt -p rsign.pub
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/rsign verify testfile.txt -p rsign.pub`
Signature and comment signature verified
Trusted comment: Just something to add to it
~/app-container/torgap-sig-cli-rust (master)
$ cargo run sign testfile.txt -t "Just something to add to it" -H
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/rsign sign testfile.txt -t 'Just something to add to it' -H`
Password: 
Deriving a key from the password and decrypting the secret key... done
~/app-container/torgap-sig-cli-rust (master)
$ cargo run verify testfile.txt -p rsign.pub
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/rsign verify testfile.txt -p rsign.pub`
Signature and comment signature verified
Trusted comment: Just something to add to it
~/app-container/torgap-sig-cli-rust (master)
$ cargo run sign testfile.txt -t "Just something to wreck a file" -H
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/rsign sign testfile.txt -t 'Just something to wreck a file' -H`
Password: 
Deriving a key from the password and decrypting the secret key... done
~/app-container/torgap-sig-cli-rust (master)
$ cargo run verify testfile.txt -p rsign.pub
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/rsign verify testfile.txt -p rsign.pub`
Signature and comment signature verified
Trusted comment: Just something to wreck a file
~/app-container/torgap-sig-cli-rust (master)
$

**Comment by gorazdko** [comment]
I think that's expected behaviour: we can just  (re)create signatures

Warning is cast out when overwriting the (secret) keys, because we cannot recreate them (since they are randomly generated).
