### ISSUE TITLE
Unclear how to obtain onion address and what is meant with 'secret'

### ISSUE THREAD

**Issue by henkvancann** [BlockchainCommons/rsign-did#4]
In MANUAL.md

"and verify a file with onion v3 address: 

**rsign verify myfile.txt --onion-address {union address}**

I was unable to retrieve the onion address from the produce of the prior command (`rsign export-to-onion-keys`), which was: _hs_ed25519_secret_key_, _hs_ed25519_public_key_ and _hostname_ 

"...in the same directory where your `secret` is."
What is exactly meant by secret?

**Comment by gorazdko** [comment]
secret key

> The secret key will be written at ~/.rsign/rsign.key. You can change the default paths with -p and -s respectively

I changed it to `secret key` now
